version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    environment:
      - FRONTEND_HOST=frontend:3000
      - BACKEND_HOST=host.docker.internal:8000
  frontend:
    image: "chatbot-ui:latest"
    ports:
      - "3000"
    secrets:
      - source: api_keys
        target: /app/.env

secrets:
  api_keys:
    file: ./.env
